initial_x: -0.01
initial_y: -0.03
initial_z: -0.01
initial_roll: 0
initial_pitch: 0
initial_yaw: 0
from: world
to: object_offset_hack
file_name: tf_keyboard_perception_offset
topic_name: /keyboard_perception_offset/keydown
