initial_x: -0.47
initial_y: -0.54
initial_z: 1.45
initial_roll: -1.7208
initial_pitch: 0.02
initial_yaw: -1.5708
from: world
to: kinect2_right_rgb_optical_frame
file_name: tf_kinect_right
topic_name: /keyboard_right/keydown
