initial_x: 0.698
initial_y: -0.43
initial_z: -0.01
initial_roll: 0.002
initial_pitch: -0.014
initial_yaw: 0.031
from: world
to: shelf
file_name: tf_keyboard_world_to_shelf
topic_name: /keyboard_world_to_shelf/keydown
